Portfolio-Desktop-Version
karam084/portfolio_desktop_version pull request #1
Opened 2021-10-28 16:13 UTC by karam084

- Create index.html file
- Create styles.css file
- Add media icons folder
- Add shapes icons folder
- Add src-image folder
- Add linter file
- Create first work card
- Create a second work card
- Create third and fourth work cards
- Create a form card about me
- Create a contact form 
- Add media queries

2021-10-29 13:44 UTC, Mihndim2020 requested changes
### Hi @karam084, 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Great job with GitHub flow
:heavy_check_mark: Good job passing linter checks

There are some issues that you still need to work on to get this project approved, but you are almost there!
![ALMOST-MINION](https://user-images.githubusercontent.com/65852621/133680327-431cb21d-ad7c-483a-84eb-21b733980a04.png)


# Status: Requires Changes ♻️
_Check the comments below under the review._

Please also consider:
- [x] Please make sure the author's(your) information is in one place in the readme file as this will make your readme file look cleaner and professional. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-30 15:56 UTC, D4nielJ requested changes
## Hello @karam084, 

Great work on making the changes requested by the previous reviewer(s) 👏

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. Please kindly fix those.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Happy coding and stay awesome! 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can always find me on slack!

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-30 15:56 UTC, D4nielJ commented on index.html
> +      <section class="content-name">
- [ ] As requested by the last reviewer, your mobile version is missing from the project. Although your desktop design is almost finished and only some details need more work. It is indispensable that you're mobile version works. That's the main point of using media queries to transform a mobile design, onto a desktop design. Kindly please fix this issue.

If you need to, you might want to take a step back, save your desktop CSS in another file and use the mobile design that you had already implemented. Then start placing the desktop CSS in your media queries again making sure that your mobile design remains intact. [You can read more on the subject in the provided lessons from Microverse.](https://github.com/microverseinc/curriculum-html-css/blob/main/responsivness.md)

![image](https://user-images.githubusercontent.com/79114233/139540240-f30319eb-3979-4da0-833c-b34835ed3010.png)

2021-10-31 00:42 UTC, Alexoid1 approved these changes
# STATUS: APPROVED!!!
## Hi @karam084  Great job! 
## Congratulations :tada: Thanks for implementing changes suggested.
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! :tada:


![brent-rambo-thumbs-up](https://user-images.githubusercontent.com/53111464/133719363-84d51903-9bd0-4ab2-94dd-7225d2862870.gif)


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-31 00:50 UTC, merged